### ISSUE TITLE
Logo proposal for rc-receiver-joystick

### ISSUE THREAD

**Issue by LuigiBaute** [patolin/rc-receiver-joystick#1]
Greetings @patolin ,

I have noticed you don't have a logo for this really cool project,
I'd like to help on that! I'm a Graphic Designer looking to
improve my portfolio (also I'm a gamer) and I like to contribute
to open source projects, if this is someting that may interest you,
let me know! :+1: 

Cheers!
-Luigi.

**Comment by patolin** [comment]
Thanks,but in this stage of the project it will not be needed. In a near future I will contact you for a contribution.

Thanks for your interest
