### ISSUE TITLE
pin mapping

### ISSUE THREAD

**Issue by cjmurph** [patolin/rc-receiver-joystick#3]
Hi,

I've got this working ok, however I can only get one channel to work.
P0 is reading and working fine, but P1 just won't work. P2 & P3 are jumpered together and P4 is used for USB comms. P5 won't work either, I think it's still fused as a reset pin on my digispark (clones).

Do you know if when using SoftRcPulseIn attach, the physical pin number is used or the analog pin number is used? I'm not sure P1 is capable of analog input. Maybe the onboard LED is causing issues on that pin.

Any ideas?

Thanks.

**Comment by cjmurph** [comment]
obviously its not an analog issue, its reading PWM. I'm an diiot.

It was the onboard LED.

I cut the trace and it's all working fine.

Might be worth making a comment about this in the readme.

**Comment by patolin** [comment]
Yes, the board is reading PPM pulses, not analog signals. Please if can you send me some pics of your board and the modifications, I can add them to the readme

**Comment by cjmurph** [comment]
This page shows the trace to cut to disable the LED.
In my case it was connected to pin 1, on some boards it's connected to pin 0.

[https://digistump.com/wiki/digispark/tutorials/modelbi2c](url)
